### ISSUE TITLE
Issue reading data

### ISSUE THREAD

**Issue by garcial359** [rydercalmdown/raspberry_pi_flight_tracker#1]
I am getting this error when I run the entrypoint.sh file.

Starting Server...
Starting Map...
pygame 2.0.1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "src/app.py", line 10, in <module>
    main()
  File "src/app.py", line 6, in main
    renderer.run_screen()
  File "/home/pi/raspberry_pi_flight_tracker/src/renderer.py", line 43, in run_screen
    for aircraft_json in decoder.get_aircraft():
  File "/home/pi/raspberry_pi_flight_tracker/src/decoder.py", line 23, in get_aircraft
    clean_up_directory()
  File "/home/pi/raspberry_pi_flight_tracker/src/decoder.py", line 16, in clean_up_directory
    for file_name in os.listdir(get_data_directory_path()):
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/raspberry_pi_flight_tracker/src/../data'

I can start the dump1090 server and see it is providing flight information, but when run from the entrypoint.sh file it doesn't seem to write a json file.

**Comment by JaxB-41** [comment]
I'm getting the same error.

**Comment by garcial359** [comment]
I figured out the issue, the program does not create the data folder.  So if you were to modify your directory structure to include a directory named "data" within the "raspberry_pi_flight_tracker" then the json files can be written in this folder.

Run this command from the raspberry_pi_flight_tracker directory to fix this issue:

mkdir data
